setup_travis

REQUIRED_XCODE_VERSION = '12.4'
default_platform :ios

fastlane_require 'behave'
fastlane_version '2.127.2'

platform :ios do
  before_all do
    verify_xcode_version(version: REQUIRED_XCODE_VERSION)
    ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '120'
  end
  
  desc 'Runs all the tests for StackOverflow'
  lane :test_all do
    reset_simulators
    clear_derived_data
    test_stackoverflow
    reset_simulators
  end
  
  private_lane :verify_xcode_version do
    ensure_xcode_version(version: REQUIRED_XCODE_VERSION)
  end
  
  desc 'This kills the Simulator process, and reset all simulators with Snapshot'
  lane :reset_simulators do
    reset_simulator_contents
  end
  
  desc 'Runs all the tests for StackOverflow'
  lane :test_stackoverflow do
    scan(scheme: 'StackOverflow', devices: ['iPhone 8'], skip_build: true, clean: false)
    sh 'mv test_output/report.junit test_output/stackoverflow_report.xml'
  end
  
  desc 'Run all the tests for StackOverflow + Coverage'
  lane :test_coverage_stackoverflow do
    test_stackoverflow
    xcov(scheme: 'StackOverflow', skip_slack: true, slack_url: '', slack_channel: 'xcovreport', slack_message: 'StackOverflow test report: Commit ' + last_git_commit[:commit_hash] + ' by ' + last_git_commit[:author], minimum_coverage_percentage: 5.0)
  end
end
